### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by amalon**
Some fixes for your consideration, first to ensure config file created on first use, 2nd to fix default port, 3rd to fix JSON detection so vibeCheck doesn't appear to fail

### CODE REVIEW

**Comment by dhghf** [comment]
The thing is the appservice will provide JSON (which describes the error) as long as the status code is not 400 so hopefully we can still get that parsed or at least print the body to the logs

**Comment by amalon** [comment]
> The thing is the appservice will provide JSON (which describes the error) as long as the status code is not 404 so hopefully we can still get that parsed or at least print the body to the logs

Thanks, that's a good point, I'll rework that last commit

**Comment by amalon** [comment]
Updated version pushed which I think resolves the error handling cases (I also tested with a bad token to check i got the errors nicely and no exceptions dumped).

**Comment by 14mRh4X0r** [comment]
Regarding the JSON fix, I've thought about (and worked on) using Gson to parse response bodies, since it's included with Minecraft anyway, see 14mRh4X0r@91949fa. I intended to create a PR for it, but I'm not quite sure whether we would want this.

**Comment by dhghf** [comment]
Gson seems more fluent when it comes to parsing bodies, we can introduce it in another PR but this one is good.

**Pull request merged**
